# Generated by Django 3.2.9 on 2021-11-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='marca',
            field=models.CharField(max_length=28, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='referencia',
            field=models.CharField(max_length=28, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(upload_to='Productos_a_vender'),
        ),
    ]
