# Generated by Django 3.2.9 on 2021-11-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_productos_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='tipo',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
