# Generated by Django 3.2.9 on 2021-11-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0004_productos_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
