# Generated by Django 3.2.9 on 2021-11-21 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0007_auto_20211119_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
