# Generated by Django 3.2.9 on 2021-11-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0008_remove_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tipo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
